-- ML Gestor — schema idempotente para Supabase/Postgres 17
create extension if not exists pgcrypto;

create or replace function public.set_updated_at() returns trigger language plpgsql set search_path='' as $$ begin new.updated_at=now(); return new; end $$;
create or replace function public.is_authorized_user() returns boolean language sql stable security invoker set search_path='' as $$
  select (select auth.uid()) is not null and coalesce((select auth.jwt()->>'email'),'')='erwinklein1994@gmail.com'
$$;

create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,user_id uuid not null unique references auth.users(id) on delete cascade,display_name text,email text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.suppliers(id uuid primary key default gen_random_uuid(),user_id uuid not null default auth.uid() references auth.users(id),name text not null,cnpj text,contact text,phone text,whatsapp text,email text,site text,address text,city text,state text,lead_time_days int default 0,minimum_order numeric(12,2) default 0,payment_terms text,shipping_notes text,notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.products(id uuid primary key default gen_random_uuid(),user_id uuid not null default auth.uid() references auth.users(id),supplier_id uuid references public.suppliers(id) on delete set null,sku text not null,name text not null,category text,status text not null default 'Em teste' check(status in ('Em teste','Ativo','Pausado','Sem estoque','Descontinuado')),cost_price numeric(12,2) not null default 0,sale_price numeric(12,2) not null default 0,total_cost numeric(12,2) default 0,expected_profit numeric(12,2) default 0,net_margin numeric(8,4) default 0,roi numeric(8,4) default 0,min_stock int not null default 0,ideal_stock int not null default 0,marketplace_url text,supplier_url text,notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(user_id,sku));
create table if not exists public.product_viability_analysis(id uuid primary key default gen_random_uuid(),user_id uuid not null default auth.uid() references auth.users(id),supplier_id uuid references public.suppliers(id) on delete set null,name text not null,category text,sku text,status text not null default 'Em estudo',input_data jsonb not null default '{}'::jsonb,result_data jsonb not null default '{}'::jsonb,notes text,approved_product_id uuid references public.products(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.product_cost_history(id uuid primary key default gen_random_uuid(),user_id uuid not null default auth.uid() references auth.users(id),product_id uuid not null references public.products(id) on delete cascade,old_value numeric(12,2),new_value numeric(12,2) not null,changed_at timestamptz not null default now());
create table if not exists public.product_price_history(id uuid primary key default gen_random_uuid(),user_id uuid not null default auth.uid() references auth.users(id),product_id uuid not null references public.products(id) on delete cascade,old_value numeric(12,2),new_value numeric(12,2) not null,changed_at timestamptz not null default now());
create table if not exists public.marketplace_fees(id uuid primary key default gen_random_uuid(),user_id uuid not null default auth.uid() references auth.users(id),name text not null,fee_type text not null check(fee_type in ('percent','fixed')),value numeric(12,4) not null default 0,is_default boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.inventory(id uuid primary key default gen_random_uuid(),user_id uuid not null default auth.uid() references auth.users(id),product_id uuid not null unique references public.products(id) on delete cascade,quantity int not null default 0 check(quantity>=0),min_stock int not null default 0,ideal_stock int not null default 0,last_entry_at timestamptz,last_exit_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.inventory_movements(id uuid primary key default gen_random_uuid(),user_id uuid not null default auth.uid() references auth.users(id),product_id uuid not null references public.products(id),movement_type text not null check(movement_type in ('entry','exit')),reason text not null,quantity int not null check(quantity>0),unit_cost numeric(12,2),reference_type text,reference_id uuid,notes text,created_at timestamptz not null default now());
create table if not exists public.sales(id uuid primary key default gen_random_uuid(),user_id uuid not null default auth.uid() references auth.users(id),order_number text,sale_date timestamptz not null default now(),status text not null default 'Concluída' check(status in ('Concluída','Cancelada','Devolvida','Parcialmente devolvida')),gross_revenue numeric(12,2) not null default 0,cost_of_goods numeric(12,2) not null default 0,marketplace_fee numeric(12,2) default 0,fixed_fee numeric(12,2) default 0,shipping_cost numeric(12,2) default 0,advertising_cost numeric(12,2) default 0,tax_cost numeric(12,2) default 0,other_cost numeric(12,2) default 0,gross_profit numeric(12,2) default 0,net_profit numeric(12,2) default 0,net_margin numeric(8,4) default 0,notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.sale_items(id uuid primary key default gen_random_uuid(),user_id uuid not null default auth.uid() references auth.users(id),sale_id uuid not null references public.sales(id) on delete cascade,product_id uuid not null references public.products(id),quantity int not null check(quantity>0),unit_price numeric(12,2) not null,unit_cost numeric(12,2) not null,line_total numeric(12,2) not null,created_at timestamptz not null default now());
create table if not exists public.sale_returns(id uuid primary key default gen_random_uuid(),user_id uuid not null default auth.uid() references auth.users(id),sale_id uuid not null references public.sales(id),sale_item_id uuid references public.sale_items(id),quantity int not null check(quantity>0),disposition text not null check(disposition in ('returned_to_stock','damaged','lost')),notes text,created_at timestamptz not null default now());
create table if not exists public.purchase_orders(id uuid primary key default gen_random_uuid(),user_id uuid not null default auth.uid() references auth.users(id),supplier_id uuid references public.suppliers(id),status text not null default 'Rascunho',order_date date,total_cost numeric(12,2) default 0,notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.purchase_items(id uuid primary key default gen_random_uuid(),user_id uuid not null default auth.uid() references auth.users(id),purchase_order_id uuid not null references public.purchase_orders(id) on delete cascade,product_id uuid not null references public.products(id),quantity int not null check(quantity>0),unit_cost numeric(12,2) not null,created_at timestamptz not null default now());
create table if not exists public.simulation_scenarios(id uuid primary key default gen_random_uuid(),user_id uuid not null default auth.uid() references auth.users(id),name text not null,scenario_data jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.monthly_targets(id uuid primary key default gen_random_uuid(),user_id uuid not null default auth.uid() references auth.users(id),month date not null,target_profit numeric(12,2) not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(user_id,month));
create table if not exists public.settings(id uuid primary key default gen_random_uuid(),user_id uuid not null default auth.uid() unique references auth.users(id),preferences jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.audit_log(id uuid primary key default gen_random_uuid(),user_id uuid not null default auth.uid() references auth.users(id),action text not null,table_name text not null,record_id uuid,old_data jsonb,new_data jsonb,created_at timestamptz not null default now());

create index if not exists idx_products_user_status on public.products(user_id,status);create index if not exists idx_sales_user_date on public.sales(user_id,sale_date desc);create index if not exists idx_inventory_user_product on public.inventory(user_id,product_id);create index if not exists idx_movements_product_date on public.inventory_movements(product_id,created_at desc);create index if not exists idx_analysis_user_status on public.product_viability_analysis(user_id,status);
create index if not exists idx_products_supplier on public.products(supplier_id);create index if not exists idx_analysis_supplier on public.product_viability_analysis(supplier_id);create index if not exists idx_analysis_approved_product on public.product_viability_analysis(approved_product_id);create index if not exists idx_cost_history_product on public.product_cost_history(product_id);create index if not exists idx_price_history_product on public.product_price_history(product_id);create index if not exists idx_sale_items_sale on public.sale_items(sale_id);create index if not exists idx_sale_items_product on public.sale_items(product_id);create index if not exists idx_sale_returns_sale on public.sale_returns(sale_id);create index if not exists idx_sale_returns_item on public.sale_returns(sale_item_id);create index if not exists idx_purchase_orders_supplier on public.purchase_orders(supplier_id);create index if not exists idx_purchase_items_order on public.purchase_items(purchase_order_id);create index if not exists idx_purchase_items_product on public.purchase_items(product_id);

do $$ declare t text; begin foreach t in array array['profiles','suppliers','products','product_viability_analysis','product_cost_history','product_price_history','marketplace_fees','inventory','inventory_movements','sales','sale_items','sale_returns','purchase_orders','purchase_items','simulation_scenarios','monthly_targets','settings','audit_log'] loop execute format('alter table public.%I enable row level security',t); execute format('drop policy if exists owner_access on public.%I',t); execute format('create policy owner_access on public.%I for all to authenticated using ((select auth.uid())=user_id and (select public.is_authorized_user())) with check ((select auth.uid())=user_id and (select public.is_authorized_user()))',t); end loop; end $$;

do $$ declare t text; begin foreach t in array array['profiles','suppliers','products','product_viability_analysis','marketplace_fees','inventory','sales','purchase_orders','simulation_scenarios','monthly_targets','settings'] loop execute format('drop trigger if exists set_%I_updated_at on public.%I',t,t); execute format('create trigger set_%I_updated_at before update on public.%I for each row execute function public.set_updated_at()',t,t); end loop; end $$;

create or replace function public.track_product_prices() returns trigger language plpgsql security invoker set search_path='' as $$ begin if old.cost_price is distinct from new.cost_price then insert into public.product_cost_history(user_id,product_id,old_value,new_value) values(new.user_id,new.id,old.cost_price,new.cost_price); end if; if old.sale_price is distinct from new.sale_price then insert into public.product_price_history(user_id,product_id,old_value,new_value) values(new.user_id,new.id,old.sale_price,new.sale_price); end if; return new; end $$;
drop trigger if exists track_product_prices on public.products;create trigger track_product_prices after update of cost_price,sale_price on public.products for each row execute function public.track_product_prices();

revoke all on function public.is_authorized_user() from public;grant execute on function public.is_authorized_user() to authenticated;
grant usage on schema public to authenticated;grant select,insert,update,delete on all tables in schema public to authenticated;alter default privileges in schema public grant select,insert,update,delete on tables to authenticated;
