import {authService,productService,supplierService,salesService,analysisService,settingsService,reportService} from './services.js';
import {products as demoProducts,suppliers as demoSuppliers,sales as demoSales} from './demo-data.js';
import {money,percent,dateBR,escapeHTML,calculateViability,viabilityLabel,uid} from './utils.js';

const AUTHORIZED_EMAIL='erwinklein1994@gmail.com';
const demoMode=new URLSearchParams(location.search).get('demo')==='1';
const state={products:[...demoProducts],suppliers:[...demoSuppliers],sales:[...demoSales],settings:{monthlyProfitTarget:7000},route:'dashboard',session:null,loading:false};
const routes=[['dashboard','⌂','Dashboard'],['analise','◇','Análise de Viabilidade'],['produtos','▦','Produtos'],['simulacao','↗','Simulação de Vendas'],['estoque','▤','Estoque'],['vendas','◉','Vendas'],['fornecedores','♧','Fornecedores'],['custos','◎','Custos e Taxas'],['relatorios','▥','Relatórios'],['configuracoes','⚙','Configurações']];
const $=s=>document.querySelector(s);const content=$('#content');
const toast=message=>{const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)};
const badge=(label,type='success')=>`<span class="badge ${type}">${escapeHTML(label)}</span>`;
const statusType=s=>s==='Sem estoque'||s==='Cancelada'?'danger':s==='Em teste'?'warning':'success';
const nav=()=>{$('#nav').innerHTML=routes.map(([id,icon,label])=>`<button data-route="${id}" class="${state.route===id?'active':''}"><span>${icon}</span>${label}</button>`).join('')};
const sum=(arr,key)=>arr.reduce((a,x)=>a+(+x[key]||0),0);

function showApp(){ $('#login-view').classList.add('hidden');$('#app').classList.remove('hidden');nav();navigate(location.hash.slice(1)||'dashboard') }
function showLogin(){ $('#app').classList.add('hidden');$('#login-view').classList.remove('hidden') }
async function loadData(){if(demoMode){const saved=localStorage.getItem('ml-gestor-settings');if(saved)state.settings={...state.settings,...JSON.parse(saved)};return}try{const [p,s,v,settings]=await Promise.all([productService.list(),supplierService.list(),salesService.list(),settingsService.get()]);state.products=p;state.suppliers=s;state.sales=v;state.settings={...state.settings,...settings}}catch(e){toast('Não foi possível carregar todos os dados. '+e.message)}}

async function boot(){
  if(demoMode){await loadData();showApp();return}
  try{state.session=await authService.session();if(state.session?.user?.email===AUTHORIZED_EMAIL){await loadData();showApp()}else{if(state.session)await authService.logout();showLogin()}}catch{showLogin()}
  authService.onChange(async session=>{state.session=session;if(session?.user?.email===AUTHORIZED_EMAIL){await loadData();showApp()}else if(!session)showLogin()});
}

$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),email=String(fd.get('email')).toLowerCase();const msg=$('#login-message');msg.textContent='';if(email!==AUTHORIZED_EMAIL){msg.textContent='Este usuário não está autorizado.';return}const btn=e.submitter;btn.disabled=true;btn.textContent='Entrando…';const {error}=await authService.login(email,fd.get('password'));btn.disabled=false;btn.textContent='Entrar no sistema';if(error)msg.textContent='E-mail ou senha inválidos.'});
$('#logout').addEventListener('click',async()=>{if(demoMode){location.href=location.pathname;return}await authService.logout()});
$('#menu-toggle').addEventListener('click',()=>$('.sidebar').classList.toggle('open'));
$('#nav').addEventListener('click',e=>{const b=e.target.closest('[data-route]');if(b)location.hash=b.dataset.route});
window.addEventListener('hashchange',()=>navigate(location.hash.slice(1)||'dashboard'));

function navigate(route){if(!routes.some(r=>r[0]===route))route='dashboard';state.route=route;nav();const info=routes.find(r=>r[0]===route);$('#page-title').textContent=info[2];$('#breadcrumb').textContent=route==='dashboard'?'VISÃO GERAL':'GESTÃO / '+info[2].toUpperCase();$('.sidebar').classList.remove('open');renderers[route]();content.focus()}

function dashboard(){const revenue=sum(state.sales,'total'),profit=sum(state.sales,'net_profit'),units=sum(state.sales,'quantity'),inventory=state.products.reduce((a,p)=>a+(+p.cost_price||0)*(+p.stock||0),0),target=+state.settings.monthlyProfitTarget||7000,targetPct=Math.min(100,profit/target*100),remaining=Math.max(0,target-profit);content.innerHTML=`
  <div class="grid metrics"><article class="metric highlight"><span class="label">Faturamento no mês</span><strong>${money(revenue)}</strong><span class="delta">↗ 12,4% vs. mês anterior</span></article><article class="metric accent"><span class="label">Lucro líquido</span><strong>${money(profit)}</strong><span class="delta">Margem média ${percent(revenue?profit/revenue*100:0)}</span></article><article class="metric"><span class="label">Unidades vendidas</span><strong>${units}</strong><span class="delta">${state.sales.length} pedidos concluídos</span></article><article class="metric"><span class="label">Capital em estoque</span><strong>${money(inventory)}</strong><span class="delta">${state.products.filter(p=>+p.stock<=+p.min_stock).length} itens pedem atenção</span></article></div>
  <div class="grid dashboard-main"><article class="panel"><div class="panel-head"><h2>Desempenho de vendas</h2><div class="tabs"><button class="tab active">7 dias</button><button class="tab">30 dias</button></div></div><div class="chart">${[38,55,48,72,65,88,76,98,83,116,106,132].map((h,i)=>`<i class="bar" style="height:${h}px"><small>${i+7}/09</small></i>`).join('')}</div></article><article class="panel"><div class="panel-head"><h2>Produtos em destaque</h2><button class="tab">Ver todos</button></div><div class="ranking">${state.products.slice(0,4).map((p,i)=>`<div class="rank"><span class="num">0${i+1}</span><div><p>${escapeHTML(p.name)}</p><small>${p.stock} un. em estoque</small><div class="progress"><i style="width:${Math.min(100,40+(+p.margin||0)*1.5)}%"></i></div></div><strong>${percent(p.margin)}</strong></div>`).join('')}</div></article></div>
  <article class="panel goal"><div><p class="eyebrow">META MENSAL DE LUCRO</p><h2>Você atingiu ${Math.round(targetPct)}% da sua meta</h2><div class="progress" style="max-width:520px"><i style="width:${targetPct}%"></i></div><p class="muted">${remaining?`Faltam ${money(remaining)} para chegar a ${money(target)}.`:'Meta mensal alcançada.'}</p></div><strong>${money(profit)}</strong></article>`}

function analyses(){content.innerHTML=`<div class="split"><form id="analysis-form" class="panel"><div class="panel-head"><h2>Nova análise</h2>${badge('Cálculo em tempo real')}</div><div class="form-grid"><label class="full">Produto<input name="name" placeholder="Ex.: Kit de ferramentas" required></label><label>Fornecedor<select name="supplier"><option value="">Selecione</option>${state.suppliers.map(s=>`<option>${escapeHTML(s.name)}</option>`).join('')}</select></label><label>Categoria<input name="category" placeholder="Ferramentas"></label><label>Custo do produto (R$)<input name="cost" type="number" step="0.01" value="80"></label><label>Preço de venda (R$)<input name="sale" type="number" step="0.01" value="169.90"></label><label>Tarifa marketplace (%)<input name="rate" type="number" step="0.01" value="16"></label><label>Impostos (%)<input name="tax" type="number" step="0.01" value="5"></label><label>Publicidade (%)<input name="ads" type="number" step="0.01" value="3"></label><label>Devoluções e perdas (%)<input name="loss" type="number" step="0.01" value="2"></label><label>Frete por unidade (R$)<input name="shipping" type="number" step="0.01" value="14"></label><label>Custos fixos (R$)<input name="fixed" type="number" step="0.01" value="5"></label><label>Embalagem (R$)<input name="packaging" type="number" step="0.01" value="2"></label><label class="full">Observações<textarea name="notes" placeholder="Demanda, concorrência e riscos observados"></textarea></label></div><div class="form-actions"><button type="button" class="btn" id="save-analysis">Salvar análise</button><button type="button" class="btn lime" id="approve-analysis">Aprovar produto</button></div></form><aside id="analysis-result" class="result-card"></aside></div>`;const form=$('#analysis-form'),result=$('#analysis-result');const update=()=>{const v=calculateViability(Object.fromEntries(new FormData(form))),[label]=viabilityLabel(v.margin);result.innerHTML=`<span class="result-status">● ${label.toUpperCase()}</span><p class="muted">Lucro líquido por unidade</p><strong class="hero-number">${money(v.profit)}</strong><dl><dt>Preço de venda</dt><dd>${money(v.sale)}</dd><dt>Custo do produto</dt><dd>${money(v.cost)}</dd><dt>Custos da venda</dt><dd>${money(v.total-v.cost)}</dd><dt>Custo total</dt><dd>${money(v.total)}</dd><dt>Margem líquida</dt><dd>${percent(v.margin)}</dd><dt>ROI</dt><dd>${percent(v.roi)}</dd><dt>Preço de equilíbrio</dt><dd>${money(v.breakEven)}</dd></dl><small>Taxas são valores de exemplo e podem ser configuradas.</small>`};form.addEventListener('input',update);update();$('#save-analysis').onclick=()=>saveAnalysis(false);$('#approve-analysis').onclick=()=>saveAnalysis(true)}
async function saveAnalysis(approve){const form=$('#analysis-form'),raw=Object.fromEntries(new FormData(form)),v=calculateViability(raw);if(!raw.name){toast('Informe o nome do produto.');return}if(approve){const p={id:uid(),sku:`PRD-${String(state.products.length+1).padStart(3,'0')}`,name:raw.name,category:raw.category||'Sem categoria',cost_price:v.cost,sale_price:v.sale,stock:0,min_stock:5,status:'Em teste',margin:v.margin,profit:v.profit};state.products.unshift(p);if(!demoMode){delete p.stock;delete p.margin;delete p.profit;await productService.save(p)}toast('Produto aprovado e adicionado ao catálogo.');location.hash='produtos'}else{if(!demoMode)await analysisService.save({name:raw.name,status:'Em estudo',input_data:raw,result_data:v});toast('Análise salva com sucesso.')}}

function products(){content.innerHTML=`<div class="page-actions"><div class="filters"><button class="tab active">Todos ${state.products.length}</button><button class="tab">Ativos</button><button class="tab">Estoque baixo</button></div><button id="new-product" class="btn primary">＋ Novo produto</button></div><div class="grid cards">${state.products.map((p,i)=>`<article class="product-card"><div class="thumb">${['🧰','📐','🗄️','🔧'][i%4]}</div><div>${badge(p.status,statusType(p.status))}<h3>${escapeHTML(p.name)}</h3><p>${escapeHTML(p.sku)} · ${escapeHTML(p.category)}</p></div><footer><div><small>Preço</small><strong>${money(p.sale_price)}</strong></div><div><small>Margem</small><strong>${percent(p.margin)}</strong></div></footer></article>`).join('')}</div><article class="panel" style="margin-top:14px"><div class="panel-head"><h2>Catálogo completo</h2><label class="search">⌕ <input id="product-search" placeholder="Pesquisar produto"></label></div>${productTable(state.products)}</article>`;$('#new-product').onclick=()=>openProductModal();$('#product-search').oninput=e=>{const q=e.target.value.toLowerCase();$('#products-body').innerHTML=productRows(state.products.filter(p=>p.name.toLowerCase().includes(q)||p.sku.toLowerCase().includes(q)))}}
const productRows=rows=>rows.map(p=>`<tr><td><strong>${escapeHTML(p.name)}</strong><small>${escapeHTML(p.category)}</small></td><td>${escapeHTML(p.sku)}</td><td>${money(p.cost_price)}</td><td>${money(p.sale_price)}</td><td>${percent(p.margin)}</td><td>${p.stock} un.</td><td>${badge(p.status,statusType(p.status))}</td><td><button class="btn" data-edit-product="${p.id}">Editar</button></td></tr>`).join('');
const productTable=rows=>`<table class="data-table"><thead><tr><th>Produto</th><th>SKU</th><th>Custo</th><th>Venda</th><th>Margem</th><th>Estoque</th><th>Status</th><th></th></tr></thead><tbody id="products-body">${productRows(rows)}</tbody></table>`;
function openProductModal(p={}){showModal(`<h2>${p.id?'Editar':'Novo'} produto</h2><form id="product-form" class="form-grid"><label class="full">Nome<input name="name" value="${escapeHTML(p.name||'')}" required></label><label>SKU<input name="sku" value="${escapeHTML(p.sku||'')}"></label><label>Categoria<input name="category" value="${escapeHTML(p.category||'')}"></label><label>Custo<input name="cost_price" type="number" step=".01" value="${p.cost_price||''}"></label><label>Preço de venda<input name="sale_price" type="number" step=".01" value="${p.sale_price||''}"></label><label>Estoque mínimo<input name="min_stock" type="number" value="${p.min_stock||5}"></label><label>Status<select name="status">${['Em teste','Ativo','Pausado','Sem estoque','Descontinuado'].map(s=>`<option ${p.status===s?'selected':''}>${s}</option>`)}</select></label><div class="form-actions full"><button class="btn primary">Salvar produto</button></div></form>`);$('#product-form').onsubmit=async e=>{e.preventDefault();const raw=Object.fromEntries(new FormData(e.currentTarget)),record={...p,id:p.id||uid(),...raw,cost_price:+raw.cost_price,sale_price:+raw.sale_price,min_stock:+raw.min_stock,stock:p.stock||0};const calc=calculateViability({cost:record.cost_price,sale:record.sale_price,rate:16,tax:5,shipping:14});record.margin=calc.margin;record.profit=calc.profit;if(!demoMode){const db={...record};delete db.stock;delete db.margin;delete db.profit;await productService.save(db)}const i=state.products.findIndex(x=>x.id===record.id);i<0?state.products.unshift(record):state.products[i]=record;$('#modal').close();toast('Produto salvo.');products()}}

function simulation(){const monthly=state.products.reduce((a,p)=>a+(+p.profit||0)*30,0);content.innerHTML=`<div class="grid metrics"><article class="metric accent"><span class="label">Lucro mensal projetado</span><strong id="sim-profit">${money(monthly)}</strong></article><article class="metric"><span class="label">Lucro anual projetado</span><strong id="sim-year">${money(monthly*12)}</strong></article><article class="metric"><span class="label">Unidades necessárias / mês</span><strong id="sim-units">${state.products.length*30}</strong></article><article class="metric"><span class="label">Capital para estoque</span><strong id="sim-capital">${money(sum(state.products,'cost_price')*30)}</strong></article></div><article class="panel" style="margin-top:14px"><div class="panel-head"><h2>Projeção por produto</h2><span class="pill dark">30 dias</span></div><table class="data-table"><thead><tr><th>Produto</th><th>Vendas/dia</th><th>30 dias</th><th>Faturamento/mês</th><th>Lucro/mês</th></tr></thead><tbody>${state.products.map(p=>`<tr><td><strong>${escapeHTML(p.name)}</strong></td><td><input class="sim-qty" data-id="${p.id}" type="number" min="0" value="1" style="width:80px"></td><td data-units="${p.id}">30</td><td data-revenue="${p.id}">${money(p.sale_price*30)}</td><td data-profit="${p.id}">${money(p.profit*30)}</td></tr>`).join('')}</tbody></table></article>`;content.querySelectorAll('.sim-qty').forEach(i=>i.oninput=updateSimulation)}
function updateSimulation(){let profit=0,capital=0,units=0;content.querySelectorAll('.sim-qty').forEach(i=>{const p=state.products.find(p=>p.id===i.dataset.id),q=(+i.value||0)*30;units+=q;profit+=(+p.profit||0)*q;capital+=(+p.cost_price||0)*q;content.querySelector(`[data-units="${p.id}"]`).textContent=q;content.querySelector(`[data-revenue="${p.id}"]`).textContent=money(p.sale_price*q);content.querySelector(`[data-profit="${p.id}"]`).textContent=money(p.profit*q)});$('#sim-profit').textContent=money(profit);$('#sim-year').textContent=money(profit*12);$('#sim-units').textContent=units;$('#sim-capital').textContent=money(capital)}

function inventory(){content.innerHTML=`<div class="grid metrics"><article class="metric"><span class="label">Itens em estoque</span><strong>${sum(state.products,'stock')}</strong></article><article class="metric accent"><span class="label">Valor pelo custo</span><strong>${money(state.products.reduce((a,p)=>a+p.stock*p.cost_price,0))}</strong></article><article class="metric"><span class="label">Estoque baixo</span><strong>${state.products.filter(p=>p.stock<=p.min_stock).length}</strong></article><article class="metric"><span class="label">Cobertura média</span><strong>18 dias</strong></article></div><article class="panel" style="margin-top:14px"><div class="panel-head"><h2>Posição de estoque</h2><button class="btn primary" id="stock-move">＋ Nova movimentação</button></div><table class="data-table"><thead><tr><th>Produto</th><th>Atual</th><th>Mínimo</th><th>Valor investido</th><th>Cobertura</th><th>Situação</th></tr></thead><tbody>${state.products.map(p=>`<tr><td><strong>${escapeHTML(p.name)}</strong><small>${p.sku}</small></td><td>${p.stock} un.</td><td>${p.min_stock} un.</td><td>${money(p.stock*p.cost_price)}</td><td>${p.stock?Math.ceil(p.stock/1.6):0} dias</td><td>${badge(p.stock===0?'Sem estoque':p.stock<=p.min_stock?'Baixo':'Normal',p.stock===0?'danger':p.stock<=p.min_stock?'warning':'success')}</td></tr>`).join('')}</tbody></table></article>`;$('#stock-move').onclick=()=>simpleModal('Nova movimentação','Registre entradas e saídas sempre por movimentação para preservar o histórico.')}

function sales(){content.innerHTML=`<div class="page-actions"><div class="filters"><button class="tab active">Todas</button><button class="tab">Concluídas</button><button class="tab">Devolvidas</button></div><button class="btn primary" id="new-sale">＋ Registrar venda</button></div><article class="panel"><table class="data-table"><thead><tr><th>Data</th><th>Pedido</th><th>Produto</th><th>Qtd.</th><th>Faturamento</th><th>Lucro líquido</th><th>Status</th></tr></thead><tbody>${state.sales.map(s=>`<tr><td>${dateBR(s.created_at)}</td><td>${escapeHTML(s.order_number||'—')}</td><td><strong>${escapeHTML(s.product||'Venda')}</strong></td><td>${s.quantity}</td><td>${money(s.total)}</td><td>${money(s.net_profit)}</td><td>${badge(s.status,statusType(s.status))}</td></tr>`).join('')}</tbody></table></article>`;$('#new-sale').onclick=openSaleModal}
function openSaleModal(){showModal(`<h2>Registrar venda</h2><form id="sale-form" class="form-grid"><label class="full">Produto<select name="product_id">${state.products.map(p=>`<option value="${p.id}">${escapeHTML(p.name)} — ${p.stock} em estoque</option>`)}</select></label><label>Quantidade<input name="quantity" type="number" min="1" value="1"></label><label>Preço vendido<input name="price" type="number" step=".01"></label><label>Número do pedido<input name="order_number" placeholder="Opcional"></label><label>Status<select name="status"><option>Concluída</option><option>Cancelada</option><option>Devolvida</option></select></label><div class="form-actions full"><button class="btn primary">Registrar e baixar estoque</button></div></form>`);$('#sale-form').onsubmit=async e=>{e.preventDefault();const r=Object.fromEntries(new FormData(e.currentTarget)),p=state.products.find(x=>x.id===r.product_id),q=+r.quantity,price=+r.price||p.sale_price;if(q>p.stock&&!confirm('A quantidade supera o estoque disponível. Confirmar mesmo assim?'))return;const sale={id:uid(),created_at:new Date().toISOString(),order_number:r.order_number,product:p.name,quantity:q,total:price*q,net_profit:(price-p.cost_price)*q,status:r.status};state.sales.unshift(sale);p.stock=Math.max(0,p.stock-q);if(!demoMode)toast('Venda preparada. Use o schema transacional para persistência atômica.');$('#modal').close();toast('Venda registrada e estoque atualizado.');sales()}}

function suppliers(){content.innerHTML=`<div class="page-actions"><p class="muted">Parceiros de compra e reposição</p><button class="btn primary" id="new-supplier">＋ Novo fornecedor</button></div><div class="grid cards">${state.suppliers.map(s=>`<article class="product-card"><div class="thumb">🏭</div><h3>${escapeHTML(s.name)}</h3><p>${escapeHTML(s.contact)} · ${escapeHTML(s.city)}/${escapeHTML(s.state)}</p><footer><div><small>Produtos</small><strong>${s.products||0}</strong></div><div><small>Prazo</small><strong>${s.lead_time_days||0} dias</strong></div></footer></article>`).join('')}</div>`;$('#new-supplier').onclick=()=>simpleModal('Novo fornecedor','Cadastre contato, prazo, condições de pagamento e pedido mínimo.')}
function costs(){content.innerHTML=`<article class="panel"><div class="panel-head"><h2>Parâmetros padrão</h2>${badge('Valores de exemplo','warning')}</div><form class="form-grid" id="fees-form"><label>Tarifa anúncio Clássico (%)<input value="16" type="number" step=".01"></label><label>Tarifa anúncio Premium (%)<input value="21" type="number" step=".01"></label><label>Imposto padrão (%)<input value="5" type="number" step=".01"></label><label>Publicidade média (%)<input value="3" type="number" step=".01"></label><label>Devoluções esperadas (%)<input value="1.5" type="number" step=".01"></label><label>Perdas esperadas (%)<input value="0.5" type="number" step=".01"></label><label>Custo de embalagem (R$)<input value="2" type="number" step=".01"></label><label>Tarifa fixa (R$)<input value="6" type="number" step=".01"></label><p class="muted full">Ajuste estes valores conforme sua operação. O sistema nunca assume que taxas de marketplace são permanentes.</p><div class="form-actions full"><button class="btn primary">Salvar parâmetros</button></div></form></article>`;$('#fees-form').onsubmit=e=>{e.preventDefault();toast('Parâmetros salvos.')}}
function reports(){content.innerHTML=`<div class="page-actions"><div class="filters"><button class="tab active">Este mês</button><button class="tab">90 dias</button><button class="tab">Ano</button></div><button id="export-sales" class="btn primary">↓ Exportar CSV</button></div><div class="grid metrics"><article class="metric accent"><span class="label">Faturamento</span><strong>${money(sum(state.sales,'total'))}</strong></article><article class="metric"><span class="label">Lucro líquido</span><strong>${money(sum(state.sales,'net_profit'))}</strong></article><article class="metric"><span class="label">Ticket médio</span><strong>${money(sum(state.sales,'total')/(state.sales.length||1))}</strong></article><article class="metric"><span class="label">ROI médio</span><strong>${percent(38.6)}</strong></article></div><article class="panel" style="margin-top:14px"><div class="panel-head"><h2>Rentabilidade por produto</h2></div>${productTable(state.products)}</article>`;$('#export-sales').onclick=()=>reportService.exportCSV(state.sales,'vendas-ml-gestor.csv')}
function settings(){content.innerHTML=`<div class="split"><article class="panel"><h2>Preferências do sistema</h2><form class="stack-form" id="settings-form" style="margin-top:18px"><label>Meta mensal de lucro<input name="monthlyProfitTarget" type="number" min="1" step="0.01" value="${+state.settings.monthlyProfitTarget||7000}" required></label><label>Dias sem giro para alerta<select name="noSalesAlertDays">${[30,60,90].map(d=>`<option value="${d}" ${+state.settings.noSalesAlertDays===d?'selected':''}>${d} dias</option>`).join('')}</select></label><label>E-mail autorizado<input value="${AUTHORIZED_EMAIL}" disabled></label><button class="btn primary">Salvar preferências</button></form></article><article class="panel"><h2>Backup e segurança</h2><p class="muted">Exporte uma cópia dos principais dados ou valide um arquivo de backup antes de importar.</p><div class="stack-form"><button id="backup" class="btn">↓ Exportar backup JSON</button><label class="btn" style="display:block;text-align:center">↑ Importar backup<input id="restore" type="file" accept="application/json" hidden></label></div></article></div>`;$('#settings-form').onsubmit=async e=>{e.preventDefault();const button=e.submitter,raw=Object.fromEntries(new FormData(e.currentTarget)),next={...state.settings,monthlyProfitTarget:+raw.monthlyProfitTarget,noSalesAlertDays:+raw.noSalesAlertDays};button.disabled=true;button.textContent='Salvando…';try{if(demoMode)localStorage.setItem('ml-gestor-settings',JSON.stringify(next));else await settingsService.save(next);state.settings=next;toast('Preferências salvas com sucesso.')}catch(error){toast('Erro ao salvar: '+error.message)}finally{button.disabled=false;button.textContent='Salvar preferências'}};$('#backup').onclick=()=>{const data=JSON.stringify({version:1,exported_at:new Date().toISOString(),products:state.products,suppliers:state.suppliers,sales:state.sales,settings:state.settings},null,2),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type:'application/json'}));a.download='ml-gestor-backup.json';a.click();URL.revokeObjectURL(a.href)};$('#restore').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(!Array.isArray(data.products)||!Array.isArray(data.sales))throw Error();state.products=data.products;state.suppliers=data.suppliers||[];state.sales=data.sales;state.settings={...state.settings,...data.settings};toast('Backup validado e importado nesta sessão.')}catch{toast('Arquivo de backup inválido.')}}}
function showModal(html){$('#modal-content').innerHTML=html;$('#modal').showModal()}
function simpleModal(title,text){showModal(`<h2>${title}</h2><p class="muted">${text}</p><div class="form-actions"><button class="btn primary" onclick="this.closest('dialog').close()">Entendi</button></div>`)}
content.addEventListener('click',e=>{const b=e.target.closest('[data-edit-product]');if(b)openProductModal(state.products.find(p=>p.id===b.dataset.editProduct))});
const renderers={dashboard,analise:analyses,produtos:products,simulacao:simulation,estoque:inventory,vendas:sales,fornecedores:suppliers,custos:costs,relatorios:reports,configuracoes:settings};
boot();
