const catalog=[
 ['Parafusadeira de Impacto 21V','Ferramentas'],['Conjunto de Ferramentas 108 peças','Ferramentas'],['Jogo de Chaves Catraca','Ferramentas'],['Alicate Universal Profissional','Ferramentas'],['Furadeira de Impacto 650W','Ferramentas'],['Serra Mármore 1300W','Ferramentas'],['Esmerilhadeira Angular 850W','Ferramentas'],['Trena Digital por Luz 40m','Medição'],['Medidor Digital Profissional','Medição'],['Multímetro Digital Automático','Medição'],
 ['Paquímetro Digital 150mm','Medição'],['Nível de Luz 12 Linhas','Medição'],['Balança Digital de Precisão','Medição'],['Termômetro Infravermelho','Medição'],['Organizador Modular 24 gavetas','Organização'],['Caixa Organizadora Empilhável','Organização'],['Estante Multiuso Reforçada','Organização'],['Maleta para Ferramentas 18 pol.','Organização'],['Painel Organizador Perfurado','Organização'],['Gaveteiro Plástico 12 Gavetas','Organização'],
 ['Leitor Automotivo sem Fio','Automotivo'],['Compressor de Ar Portátil','Automotivo'],['Carregador de Bateria 12V','Automotivo'],['Conjunto para Limpeza Automotiva','Automotivo'],['Câmera de Ré em Alta Definição','Automotivo'],['Suporte Veicular Magnético','Automotivo'],['Inflador Digital de Pneus','Automotivo'],['Cabo Auxiliar de Partida','Automotivo'],['Lanterna Recarregável','Casa e Jardim'],['Mangueira Expansível 15m','Casa e Jardim'],
 ['Pulverizador Manual 5L','Casa e Jardim'],['Conjunto de Irrigação por Gotejamento','Casa e Jardim'],['Luminária Solar de Parede','Casa e Jardim'],['Fechadura Digital Biométrica','Casa e Jardim'],['Sensor de Presença sem Fio','Eletrônicos'],['Câmera sem Fio em Alta Definição','Eletrônicos'],['Tomada Inteligente sem Fio','Eletrônicos'],['Adaptador de Conexões 7 em 1','Eletrônicos'],['Carregador Rápido 65W','Eletrônicos'],['Suporte Articulado para Monitor','Eletrônicos'],
 ['Teclado Mecânico Compacto','Eletrônicos'],['Dispositivo Apontador sem Fio','Eletrônicos'],['Fone sem Fio com Microfone','Eletrônicos'],['Mochila para Computador Portátil 17 pol.','Acessórios'],['Bolsa Térmica 20 Litros','Acessórios'],['Garrafa Térmica de Aço 1L','Acessórios'],['Cinta Ergonômica Lombar','Segurança'],['Óculos de Proteção Antiembaçante','Segurança'],['Luva Anticorte Nível 5','Segurança'],['Protetor Auricular Tipo Concha','Segurança']
];
export const products=catalog.map(([name,category],i)=>{const cost=35+(i*17%180)+(i%3)*.9,sale=+(cost*(1.72+(i%5)*.06)).toFixed(2),fees=sale*.24+9,profit=+(sale-cost-fees).toFixed(2);return{id:String(i+1),sku:`DEMO-${String(i+1).padStart(3,'0')}`,name,category,cost_price:+cost.toFixed(2),sale_price:sale,stock:i%13===0?0:5+(i*7%43),min_stock:8+(i%6),status:i%13===0?'Sem estoque':i%11===0?'Em teste':'Ativo',margin:+(profit/sale*100).toFixed(2),profit}});
export const suppliers=[{id:'1',name:'Atlas Distribuidora',contact:'Marina Costa',city:'Campinas',state:'SP',lead_time_days:4,products:12},{id:'2',name:'Norte Ferramentas',contact:'Rafael Souza',city:'Guarulhos',state:'SP',lead_time_days:6,products:10},{id:'3',name:'Vetor Importações',contact:'Bianca Lima',city:'Curitiba',state:'PR',lead_time_days:9,products:9},{id:'4',name:'Orbital Atacado',contact:'Lucas Mendes',city:'Joinville',state:'SC',lead_time_days:7,products:8},{id:'5',name:'Ponto Inteligente Distribuição',contact:'Aline Rocha',city:'São Paulo',state:'SP',lead_time_days:3,products:11}];
export const sales=Array.from({length:120},(_,i)=>{const p=products[(i*7)%products.length],quantity=1+(i%4),total=+(p.sale_price*quantity).toFixed(2);return{id:`v${i+1}`,created_at:new Date(2026,8,19-(i%75),10+(i%8)).toISOString(),order_number:`ML-DEMO-${String(1001+i).padStart(5,'0')}`,product:p.name,quantity,total,net_profit:+(p.profit*quantity).toFixed(2),status:i%31===0?'Devolvida':i%23===0?'Cancelada':'Concluída'}});
